--DO AN ATBM HTTT
--PHAN HE 1
--MSSV: 21127634 - Mach Vi Kiet
--MSSV: 21127609 - Nguyen Duc Vinh Hoa
--MSSV: 21127641 - Nguyen Xuan Loc
--MSSV: 21127660 - Doan Thi Yen Nhi
--DATABASE
--TAO BANG NHAN SU
CREATE TABLE QL_TRUONGHOC_X.NHANSU (
    MANV char(10),
    HOTEN varchar2(100),
    PHAI char(1), 
    NGAYSINH date,
    PHUCAP number(10,0),
    DT char(10),
    VAITRO varchar2(100), 
    MADV char(5),
    
    CONSTRAINT NHANSU_PK PRIMARY KEY(MANV)
);

--TAO BANG SINH VIEN
CREATE TABLE QL_TRUONGHOC_X.SINHVIEN (
    MASV varchar2(8),
    HOTEN varchar2(100),
    PHAI char(1),  -- Y or N
    NGAYSINH date,
    DIACHI varchar2(400),
    DT char(10),
    MACT char(5),
    MANGANH char(5),
    SOTCTL number(3,0),
    DTBTL number(4,2), 
    
    CONSTRAINT SINHVIEN_PK PRIMARY KEY(MASV)
);

--TAO BANG DON VI
CREATE TABLE QL_TRUONGHOC_X.DONVI(
    MADV char(5),
    TENDV varchar2(100),
    TRUONGDONVI char(5),
    
    CONSTRAINT DONVI_PK PRIMARY KEY(MADV)
);

--TAO BANG HOC PHAN
CREATE TABLE QL_TRUONGHOC_X.HOCPHAN (
    MAHP char(5),
    TENHP varchar(100),
    SOTC number(2,0),
    STLT number(2,0),
    STTH number(2,0),
    SOSVTD number(3,0),
    MADV char(5),
    
    CONSTRAINT HOCPHAN_PK PRIMARY KEY(MAHP)
);

--TAO BANG KHMO 
CREATE TABLE QL_TRUONGHOC_X.KHMO (
    MAHP char(5),
    HK number(1,0),
    NAM varchar(4),
    MACT varchar(4), -- CQ, CLC, CTTT, VP
    
    CONSTRAINT KHMO_PK PRIMARY KEY(MAHP, HK, NAM, MACT)
);
--TAO BANG PHAN CONG
CREATE TABLE QL_TRUONGHOC_X.PHANCONG (
    MAGV char(5), 
    MAHP char(5),
    HK number (1,0),
    NAM varchar(4),
    MACT varchar(4),  -- CQ, CLC, CTTT, VP
    
    CONSTRAINT PHANCONG_PK PRIMARY KEY(MAGV,MAHP,HK,NAM,MACT)
);

--TAO BANG DANGKY
CREATE TABLE QL_TRUONGHOC_X.DANGKY (
    MASV varchar2(8),
    MAGV char(5), 
    MAHP char(5),
    HK number (1,0),
    NAM varchar(4),
    MACT varchar(4),  -- CQ, CLC, CTTT, VP
    DIEMTH number (4,2),
    DIEMQT number (4,2),
    DIEMCK number(4,2),
    DIEMTK number (4,2),

    CONSTRAINT DANGKY_PK PRIMARY KEY(MASV,MAGV,MAHP,HK,NAM,MACT)
);

--TAO KHOA NGOAI 
ALTER TABLE QL_TRUONGHOC_X.NHANSU
ADD
    CONSTRAINT FK_NHANSU_DONVI
    FOREIGN KEY (MADV)
    REFERENCES QL_TRUONGHOC_X.DONVI(MADV);

ALTER TABLE QL_TRUONGHOC_X.DONVI
ADD
    CONSTRAINT FK_DONVI_NHANSU
    FOREIGN KEY (TRUONGDONVI)
    REFERENCES QL_TRUONGHOC_X.NHANSU(MANV);

ALTER TABLE QL_TRUONGHOC_X.HOCPHAN 
ADD
    CONSTRAINT FK_HOCPHAN_DONVI
    FOREIGN KEY (MADV) 
    REFERENCES QL_TRUONGHOC_X.DONVI(MADV);

ALTER TABLE QL_TRUONGHOC_X.PHANCONG
ADD 
    CONSTRAINT FK_PHANCONG_NHANSU
    FOREIGN KEY (MAGV)
    REFERENCES QL_TRUONGHOC_X.NHANSU(MANV);
ALTER TABLE QL_TRUONGHOC_X.PHANCONG   
ADD    
    CONSTRAINT FK_PHANCONG_KHMO
    FOREIGN KEY (MAHP, HK, NAM, MACT)
    REFERENCES QL_TRUONGHOC_X.KHMO(MAHP, HK, NAM, MACT);

ALTER TABLE QL_TRUONGHOC_X.KHMO
ADD
    CONSTRAINT FK_KHMO_HOCPHAN
    FOREIGN KEY (MAHP)
    REFERENCES QL_TRUONGHOC_X.HOCPHAN(MAHP);
    
ALTER TABLE QL_TRUONGHOC_X.DANGKY
ADD
    CONSTRAINT FK_DANGKY_SINHVIEN
    FOREIGN KEY (MASV)
    REFERENCES QL_TRUONGHOC_X.SINHVIEN(MASV);
ALTER TABLE QL_TRUONGHOC_X.DANGKY
ADD    
    CONSTRAINT FK_DANGKY_PHANCONG
    FOREIGN KEY (MAGV, MAHP, HK, NAM, MACT)
    REFERENCES QL_TRUONGHOC_X.PHANCONG(MAGV, MAHP, HK, NAM, MACT);
    